version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8000:8081
  app-pm2:
    container_name: app-pm2
    #构建容器
    build: ./service
    ports:
      - "3000:3000"
  nginx:
    restart: always
    image: nginx
    ports:
      - 8092:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./vue-admin/dist:/var/www/html/
      - ./vue-admin/static/:/static/